# Generated by Django 5.0.2 on 2024-02-12 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Comment', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=25)),
                ('Phone', models.BigIntegerField()),
                ('Address', models.CharField(max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('admin_comment', models.CharField(default='Account created. Under verification.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FEEDBACK_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RATINGS', models.CharField(max_length=300)),
                ('COMMENT', models.CharField(default='', max_length=300)),
                ('L_ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=25)),
                ('Pro_image', models.ImageField(upload_to='photos')),
                ('Pro_description', models.CharField(max_length=500)),
                ('Pro_price', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('Pro_Cat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='product_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=300)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('Price', models.IntegerField(default=100)),
                ('Quantity', models.IntegerField()),
                ('Final_price', models.IntegerField()),
                ('Order_id', models.IntegerField(default=0)),
                ('Order_status', models.IntegerField(default=0)),
                ('L_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('Product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='product_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=35)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed')], max_length=50)),
                ('Payment_status', models.CharField(max_length=30)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='product_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_subcategory_name', models.CharField(max_length=25)),
                ('Pro_Cat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.product_category')),
            ],
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Pro_subcat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.product_subcategory'),
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('owner_id', models.ImageField(upload_to='photos')),
                ('is_verified', models.BooleanField(default=False)),
                ('L_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
