# Generated by Django 5.0.2 on 2024-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
