# Generated by Django 5.0.2 on 2024-02-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_certificate',
            field=models.ImageField(default='', upload_to='photos'),
        ),
    ]
