# Generated by Django 5.0.2 on 2024-02-15 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_shop_shop_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='L_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
