# Generated by Django 5.0.2 on 2024-02-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_detail_l_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
