# Generated by Django 5.0.2 on 2024-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_detail_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='Pro_brandname',
            field=models.CharField(default='Prexa Wear', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='Pro_name',
            field=models.CharField(max_length=70),
        ),
    ]
