# Generated by Django 5.0.2 on 2024-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_detail_pro_brandname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='Name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='product_order',
            name='Phone',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
