# Generated by Django 5.0.2 on 2024-02-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_order_name_product_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
