# Generated by Django 5.1.6 on 2025-03-31 10:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.IntegerField(default=0)),
                ('Name', models.CharField(default='', max_length=35)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Phone', models.CharField(default='', max_length=35)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('Payment_status', models.CharField(default='Pending', max_length=30)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 4, 7, 10, 9, 4, 910760, tzinfo=datetime.timezone.utc))),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.DeleteModel(
            name='product_order',
        ),
    ]
