# Generated by Django 5.1.6 on 2025-03-31 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_productorder_delete_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.IntegerField(default=0)),
                ('Name', models.CharField(default='', max_length=35)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Phone', models.CharField(default='', max_length=35)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('Payment_status', models.CharField(max_length=30)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
