# Generated by Django 5.1.6 on 2025-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_product_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='Total_amount',
            field=models.FloatField(),
        ),
    ]
