# Generated by Django 5.1.6 on 2025-04-01 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_product_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_order',
            old_name='Total_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='product_order',
            old_name='L_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Date_time',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Payment_status',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='product_order',
            name='offline_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_order',
            name='offline_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_order',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'Online Payment'), ('offline', 'Offline Payment')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='product_order',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
