# Generated by Django 5.1.6 on 2025-04-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_total_amount_product_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_order',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
