# Generated by Django 5.1.6 on 2025-04-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='L_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
