# Generated by Django 5.1.6 on 2025-04-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_image_l_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='Pro_image',
        ),
    ]
