# Generated by Django 5.1.6 on 2025-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_product_detail_pro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='Pro_image',
            field=models.ImageField(default=0, upload_to='photos'),
            preserve_default=False,
        ),
    ]
