from django.urls import path, include
from myapp import views

urlpatterns = [
   path("", views.index, name="index"),
   path("loginsignup", views.login_signup, name="loginsignup"),
   path("contactus", views.contactus, name="contactus"),
   path("submitcontact", views.submitcontact, name="submitcontact"),
   path("viewdata", views.viewdata, name="viewdata"),
   path("checkuser", views.checklogin, name="checkuser"),
   path("logout", views.logout, name="logout"),
   path("yourprofile", views.yourprofile, name="yourprofile"),
   path("editprofilesubmit", views.editprofilesubmit, name="editprofilesubmit"),
   path("changepwd", views.changepwd, name="changepwd"),
   path("completeprofilesubmit", views.completeprofilesubmit, name="completeprofilesubmit"),
   path("editcompleteprofilesubmit", views.editcompleteprofilesubmit, name="editcompleteprofilesubmit"),
   path("addproduct", views.addproduct, name="addproduct"),
   path("allproducts", views.allproducts, name="allproducts"),
   path("searchresults", views.searchresults, name="searchresults"),
   path("addtocart", views.addtocart, name="addtocart"),
   path("mycart", views.mycart, name="mycart"),
   path('payment-status/', views.success, name='payment_status'),
   path("myorders", views.myorders, name="myorders"),
   path("sellerorders", views.sellerorders, name="sellerorders"),
   path("singleorder/<int:yoid>", views.singleorder, name="singleorder"),
   path("singleorderseller/<int:syoid>", views.singleorderseller, name="singleorderseller"),
   path("cancelorder/<int:coid>", views.cancelorder, name="cancelorder"),
   path("checkout", views.checkout, name="checkout"),
   path("placeorder", views.placeorder, name="placeorder"),
   path("orderplaced", views.orderplaced, name="orderplaced"),
   path("submitreview", views.SubmitReview, name="submitreview"),
   path("addproductsubmit", views.addproductsubmit, name="addproductsubmit"),
   path("manageproduct", views.manageproduct, name="manageproduct"),
   path("editproductdetails", views.editproductdetails, name="editproductdetails"),
   path('get_subcategories/', views.get_subcategories, name='get_subcategories'),
   path("editproduct/<int:epid>", views.editproduct, name="editproduct"),
   path("removefromcart/<int:rcid>", views.removefromcart, name="removefromcart"),
   path("removeprod/<int:rpid>", views.removeprod, name="removeprod"),
   path("catwiseprod/<int:cpid>", views.catwiseprod, name="catwiseprod"),
   path("subcatprod/<int:scpid>", views.subcatprod, name="subcatprod"),
   path("viewprod/<int:pdid>", views.viewprod, name="viewprod"),
   path("add_product_image", views.add_product_image, name="add_product_image"),
   path("register",views.registerpage),

]